# Generated by Django 5.2.1 on 2025-05-21 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Table number or identifier')),
                ('seats', models.PositiveIntegerField(help_text='Number of seats at this table (min 4, max 10)', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'number'],
                'unique_together': {('restaurant', 'number')},
            },
        ),
    ]
